In [ ]:
################################################################################################################################################
################################################################################################################################################
############################################# PROGRAM TO CREATE LINEAR REGRESSION MODEL ########################################################
################################################################################################################################################
################################################################################################################################################

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats


In [2]:
################################################ Read the Housing Data CSV file ##############################################################
column_names = ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE',
                'DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV']

""" Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
        - B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
        - LSTAT    % lower status of the population
        - MEDV     Median value of owner-occupied homes in $1000's
 """
data_boston = pd.read_csv("../data/housing.csv", header=None, delimiter=r"\s+", names=column_names)
data_boston.head(20)

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
0   0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296.0   
1   0.02731   0.0   7.07     0  0.469  6.421   78.9  4.9671    2  242.0   
2   0.02729   0.0   7.07     0  0.469  7.185   61.1  4.9671    2  242.0   
3   0.03237   0.0   2.18     0  0.458  6.998   45.8  6.0622    3  222.0   
4   0.06905   0.0   2.18     0  0.458  7.147   54.2  6.0622    3  222.0   
5   0.02985   0.0   2.18     0  0.458  6.430   58.7  6.0622    3  222.0   
6   0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5  311.0   
7   0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5  311.0   
8   0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5  311.0   
9   0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5  311.0   
10  0.22489  12.5   7.87     0  0.524  6.377   94.3  6.3467    5  311.0   
11  0.11747  12.5   7.87     0  0.524  6.009   82.9  6.2267    5  311.0   
12  0.09378  12.5   7.87     0  0.524  5.889   39.0  5.4509    5  311.0   
13  0.62976   0.0   8.14     0  0.538  5.949   61.8  4.7075    4  307.0   
14  0.63796   0.0   8.14     0  0.538  6.096   84.5  4.4619    4  307.0   
15  0.62739   0.0   8.14     0  0.538  5.834   56.5  4.4986    4  307.0   
16  1.05393   0.0   8.14     0  0.538  5.935   29.3  4.4986    4  307.0   
17  0.78420   0.0   8.14     0  0.538  5.990   81.7  4.2579    4  307.0   
18  0.80271   0.0   8.14     0  0.538  5.456   36.6  3.7965    4  307.0   
19  0.72580   0.0   8.14     0  0.538  5.727   69.5  3.7965    4  307.0   

    PTRATIO       B  LSTAT  MEDV  
0      15.3  396.90   4.98  24.0  
1      17.8  396.90   9.14  21.6  
2      17.8  392.83   4.03  34.7  
3      18.7  394.63   2.94  33.4  
4      18.7  396.90   5.33  36.2  
5      18.7  394.12   5.21  28.7  
6      15.2  395.60  12.43  22.9  
7      15.2  396.90  19.15  27.1  
8      15.2  386.63  29.93  16.5  
9      15.2  386.71  17.10  18.9  
10     15.2  392.52  20.45  15.0  
11     15.2  396.90  13.27  18.9  
12     15.2  390.50  15.71  21.7  
13     21.0  396.90   8.26  20.4  
14     21.0  380.02  10.26  18.2  
15     21.0  395.62   8.47  19.9  
16     21.0  386.85   6.58  23.1  
17     21.0  386.75  14.67  17.5  
18     21.0  288.99  11.69  20.2  
19     21.0  390.95  11.28  18.2

In [9]:
##################################### Define Dependent and Independent Attributes ##########################################################
df = data_boston.drop(columns=["MEDV"])
df.head(10)

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421   78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185   61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998   45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147   54.2  6.0622    3  222.0   
5  0.02985   0.0   2.18     0  0.458  6.430   58.7  6.0622    3  222.0   
6  0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5  311.0   
7  0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5  311.0   
8  0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5  311.0   
9  0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5  311.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33  
5     18.7  394.12   5.21  
6     15.2  395.60  12.43  
7     15.2  396.90  19.15  
8     15.2  386.63  29.93  
9     15.2  386.71  17.10

In [10]:
target = data_boston[["MEDV"]]
target.head(10)

MEDV
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9

In [11]:
##################################### Create Linear Regression Model ##########################################################
from sklearn.linear_model import LinearRegression  
lm = LinearRegression()
lm.fit(df, target)

LinearRegression()

In [12]:
# Co-efficients & Intercept
print('Intercept: \n', lm.intercept_)
print('Coefficients: \n', lm.coef_)

Intercept: 
 [36.45948839]
Coefficients: 
 [[-1.08011358e-01  4.64204584e-02  2.05586264e-02  2.68673382e+00
  -1.77666112e+01  3.80986521e+00  6.92224640e-04 -1.47556685e+00
   3.06049479e-01 -1.23345939e-02 -9.52747232e-01  9.31168327e-03
  -5.24758378e-01]]


In [13]:
# R-Sqaure
lm.score(df, target)

0.7406426641094094

In [14]:
coeff_df = pd.DataFrame({'Variable': np.append('Intercept', df.columns.to_numpy()), 'Coefficient': np.append(lm.intercept_,lm.coef_)}) 
coeff_df  

Variable  Coefficient
0   Intercept    36.459488
1        CRIM    -0.108011
2          ZN     0.046420
3       INDUS     0.020559
4        CHAS     2.686734
5         NOX   -17.766611
6          RM     3.809865
7         AGE     0.000692
8         DIS    -1.475567
9         RAD     0.306049
10        TAX    -0.012335
11    PTRATIO    -0.952747
12          B     0.009312
13      LSTAT    -0.524758

In [15]:
#################################### Linear Regression Using StatModels #########################################################
import statsmodels.api as sm
model = sm.OLS(target, df).fit()

In [16]:
# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                   MEDV   R-squared (uncentered):                   0.959
Model:                            OLS   Adj. R-squared (uncentered):              0.958
Method:                 Least Squares   F-statistic:                              891.3
Date:                Sat, 17 Aug 2024   Prob (F-statistic):                        0.00
Time:                        15:43:34   Log-Likelihood:                         -1523.8
No. Observations:                 506   AIC:                                      3074.
Df Residuals:                     493   BIC:                                      3128.
Df Model:                          13                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
CRIM          -0.0929      0.034     -2.699      0.007      -0.161      -0.025
ZN             0.0487      0.014      3.382      0.001       0.020       0.077
INDUS         -0.0041      0.064     -0.063      0.950      -0.131       0.123
CHAS           2.8540      0.904      3.157      0.002       1.078       4.630
NOX           -2.8684      3.359     -0.854      0.394      -9.468       3.731
RM             5.9281      0.309     19.178      0.000       5.321       6.535
AGE           -0.0073      0.014     -0.526      0.599      -0.034       0.020
DIS           -0.9685      0.196     -4.951      0.000      -1.353      -0.584
RAD            0.1712      0.067      2.564      0.011       0.040       0.302
TAX           -0.0094      0.004     -2.395      0.017      -0.017      -0.002
PTRATIO       -0.3922      0.110     -3.570      0.000      -0.608      -0.176
B              0.0149      0.003      5.528      0.000       0.010       0.020
LSTAT         -0.4163      0.051     -8.197      0.000      -0.516      -0.317
==============================================================================
Omnibus:                      204.082   Durbin-Watson:                   0.999
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1374.225
Skew:                           1.609   Prob(JB):                    3.90e-299
Kurtosis:                      10.404   Cond. No.                     8.50e+03
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 8.5e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [17]:
################################# Add Intercept and Refit the model ###########################################
df_withconstant = sm.add_constant(df) ## let's add an intercept (beta_0) to our model
df_withconstant.head()

const     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    1.0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    1.0  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    1.0  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    1.0  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    1.0  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [18]:
# Execute linear Regression. Note the difference in argument order
model = sm.OLS(target, df_withconstant).fit()

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   MEDV   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.734
Method:                 Least Squares   F-statistic:                     108.1
Date:                Sat, 17 Aug 2024   Prob (F-statistic):          6.72e-135
Time:                        15:43:34   Log-Likelihood:                -1498.8
No. Observations:                 506   AIC:                             3026.
Df Residuals:                     492   BIC:                             3085.
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         36.4595      5.103      7.144      0.000      26.432      46.487
CRIM          -0.1080      0.033     -3.287      0.001      -0.173      -0.043
ZN             0.0464      0.014      3.382      0.001       0.019       0.073
INDUS          0.0206      0.061      0.334      0.738      -0.100       0.141
CHAS           2.6867      0.862      3.118      0.002       0.994       4.380
NOX          -17.7666      3.820     -4.651      0.000     -25.272     -10.262
RM             3.8099      0.418      9.116      0.000       2.989       4.631
AGE            0.0007      0.013      0.052      0.958      -0.025       0.027
DIS           -1.4756      0.199     -7.398      0.000      -1.867      -1.084
RAD            0.3060      0.066      4.613      0.000       0.176       0.436
TAX           -0.0123      0.004     -3.280      0.001      -0.020      -0.005
PTRATIO       -0.9527      0.131     -7.283      0.000      -1.210      -0.696
B              0.0093      0.003      3.467      0.001       0.004       0.015
LSTAT         -0.5248      0.051    -10.347      0.000      -0.624      -0.425
==============================================================================
Omnibus:                      178.041   Durbin-Watson:                   1.078
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              783.126
Skew:                           1.521   Prob(JB):                    8.84e-171
Kurtosis:                       8.281   Cond. No.                     1.51e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.51e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [19]:
""" ######################################## Perform Step wise Linear Regression #####################################################
from mlxtend.feature_selection import SequentialFeatureSelector

sfs = SequentialFeatureSelector(LinearRegression(), k_features=4, forward=True, verbose=1,scoring="neg_mean_squared_error")
selected_features = sfs.fit(df, target)

### Need to install mlxtend library ### """

' ######################################## Perform Step wise Linear Regression #####################################################\nfrom mlxtend.feature_selection import SequentialFeatureSelector\n\nsfs = SequentialFeatureSelector(LinearRegression(), k_features=4, forward=True, verbose=1,scoring="neg_mean_squared_error")\nselected_features = sfs.fit(df, target)\n\n### Need to install mlxtend library ### '

In [21]:
#################################### Mean Squared Error of the Model ###############################################################
from sklearn.metrics import mean_squared_error
predictions = lm.predict(df)
predictions[1:10]

array([[25.02556238],
       [30.56759672],
       [28.60703649],
       [27.94352423],
       [25.25628446],
       [23.00180827],
       [19.53598843],
       [11.52363685],
       [18.92026211]])

In [23]:
mse2 = mean_squared_error(target,predictions)
print("Mean square error is:", mse2)

Mean square error is: 21.894831181729206


In [24]:
###################################################################################################################################
##################################### Model Evaluation on Training and Testing Data ###############################################
###################################################################################################################################

from sklearn.model_selection import train_test_split

############################ Split the data into test and training (15% as test data) #############################################
x_train, x_test, y_train, y_test = train_test_split(df, target, test_size=0.15, random_state=10)

In [25]:
print("Number of test samples :", x_test.shape[0])
print("Number of training samples:",x_train.shape[0])

Number of test samples : 76
Number of training samples: 430


In [26]:
################################### Fit (Train) the model using the training data ##############################################
lm_train = LinearRegression()
lm_train.fit(x_train,y_train)


LinearRegression()

In [27]:
######################################## Prediction using Training Data ########################################################
predictions_train = lm_train.predict(x_train)
print(predictions_train[0:5])

[[38.50466036]
 [ 8.24724764]
 [18.28981594]
 [30.23698109]
 [22.67291665]]


In [28]:
######################################## Prediction using Test Data ############################################################
predictions_test = lm_train.predict(x_test)
print(predictions_test[0:5])

[[30.88964438]
 [31.80456557]
 [30.77368612]
 [22.23594312]
 [18.66336652]]


In [30]:
######################################### Model accuracy using Training Data ###################################################
mse_train = mean_squared_error(y_train,predictions_train)
print("Mean square error is",mse_train)
print("R-Square value using training data is", lm_train.score(x_train,y_train))

Mean square error is 19.29593358353971
R-Square value using training data is 0.7469674747271953


In [31]:
########################################### Model accuracy using Test Data #####################################################
mse_test = mean_squared_error(y_test,predictions_test)
print("Mean square error is",mse_test)
print("R-Square value using test data is", lm_train.score(x_test,y_test))

Mean square error is 38.401262752112544
R-Square value using test data is 0.6622047563270379


In [32]:
###############################################################################################################################
############################################### K-Fold Cross Validation #######################################################
###############################################################################################################################
from sklearn.model_selection import cross_val_score, KFold

rcross = cross_val_score(lm, df, target, cv=KFold(n_splits=5,shuffle=True))

print(rcross)
print("The mean of the folds are", rcross.mean())

[0.72536426 0.77705059 0.66182291 0.71846989 0.63646701]
The mean of the folds are 0.7038349317036057
